general_settings:
  block_robots: true
  store_model_in_db: true

router_settings:
  num_retries: 3

litellm_settings:
  set_verbose: false
  cache: false
  drop_params: true

model_list:
  - model_name: github-copilot/gpt-5.2-codex
    model_info:
      mode: responses
    litellm_params:
      model: github_copilot/gpt-5.2-codex
      extra_headers:
        editor-version: "vscode/1.95.0"
        editor-plugin-version: "copilot-chat/0.26.7"

  - model_name: github-copilot/gpt-5-mini
    model_info:
      mode: responses
    litellm_params:
      model: github_copilot/gpt-5-mini
      extra_headers:
        editor-version: "vscode/1.95.0"
        editor-plugin-version: "copilot-chat/0.26.7"

  - model_name: github-copilot/claude-opus-4.5
    litellm_params:
      model: github_copilot/claude-opus-4.5
      extra_headers:
        editor-version: "vscode/1.95.0"
        editor-plugin-version: "copilot-chat/0.26.7"

  - model_name: github-copilot/gemini-3-pro-preview
    litellm_params:
      model: github_copilot/gemini-3-pro-preview
      extra_headers:
        editor-version: "vscode/1.95.0"
        editor-plugin-version: "copilot-chat/0.26.7"
